### PR TITLE
Implement alarms

### PR DESCRIPTION
**Pull request by captainhorsepower**

### CODE REVIEW

**Comment by kelidon** [comment]
that's good, thanks

**Comment by kelidon** [comment]
it would be fine to make a button for an alarm
with settings opening on click, where you could set time

**Comment by captainhorsepower** [comment]
sounds reasonable,
but I'm fine with what is there now (in terms of functionality)
It's kinda satisfying to see precisely how much time left until alarm

**Comment by captainhorsepower** [comment]
I deleted this branch, for use new one for future updates.

**Pull request merged**
